---
- name: Add LAG for leafs
  hosts: Leafs_DC1, Leafs_DC2
  tasks:
  - name: Add a LAG for MLAG
    arista.eos.eos_lag_interfaces:
      config:
      - name: 2000
        members:
        - member: Ethernet1
          mode: active
        - member: Ethernet2
          mode: active
      state: merged
