---
servers:
  host1-DC2:
    adapters:
    - type: server
      server_ports: [ E1, E2, E3, E4]
      switches: [leaf1-DC2, leaf1-DC2, leaf2-DC2, leaf2-DC2]
      switch_ports: [ Ethernet6, Ethernet7, Ethernet6, Ethernet7]
      vlans: 10
      mode: access
      spanning_tree_portfast: edge
      port_channel:
        description: host`-DC1
        mode: active
  host2-DC2:
    adapters:
    - type: server
      server_ports: [ E1, E2, E3, E4]
      switches: [leaf3-DC2, leaf3-DC2, leaf4-DC2, leaf4-DC2]
      switch_ports: [ Ethernet6, Ethernet7, Ethernet6, Ethernet7]
      vlans: 20
      mode: access
      spanning_tree_portfast: edge
      port_channel:
        description: host2-DC1
        mode: active
