---
- name: Generate interface configs (p2p, loopback)
  hosts: DC1, DC2
  tasks:
  - name: Load variables into local dictionary
    include_vars:
      file: ../vars/EVPN_model.yml
      name: EVPN
  - name: Generate BGP config
    template:
      src: "{{ lookup('env','PWD') }}/templates/EVPN_interfaces.j2"
      dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}_interface.cfg"
