---
- name: Generate BGP config from template
  hosts: spine1-DC1, spine2-DC1, spine1-DC2, spine2-DC2
  tasks:
  - name: Load variables into local dictionary
    include_vars:
      file: ../vars/L2LS_model.yml
      name: L2LS
  - name: Generate BGP config
    template:
      src: "{{ lookup('env','PWD') }}/templates/L2LS_spine.j2"
      dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}_L2LS.cfg"